### ISSUE TITLE
Думаю есть смысл продублировать твою подборку на GitFlic.

### ISSUE THREAD

**Issue by Andry2017** [e2k-community/awesome-e2k#29]
Думаю есть смысл продублировать твою подборку на GitFlic так как есть риски что GitHub может стать недоступен.

**Comment by cyfive** [comment]
Я пока думаю, или свой хостинг сделать или gitflic или еще какой дружественный использовать. Пока просто локально забекапил все репо.

**Comment by cyfive** [comment]
Настроил бекуапы локально, пока дублировать не буду.
